version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_EXPOSE_PORT}:5432"
    volumes:
      - db:/var/lib/postgresql/data/

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMIN_EXPOSE_PORT}:8080

  node:
    image: flightline-client:latest
    command: ./development-startup.sh
    environment:
      - TYPE_RUN_APP=${TYPE_RUN_APP}
    ports:
      - ${APP_EXPOSE_PORT}:3000
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/project
    restart: always
    networks:
      - master-cloud

volumes:
  db:
    driver: local

networks:
  master-cloud:
    external:
      name: master-cloud