version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cloud-master
    ports:
      - "4040:5432"
    volumes:
      - db:/var/lib/postgresql/data/

  adminer:
    image: adminer
    restart: always
    ports:
      - 4050:8080

  node:
    image: "node:18"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - 5000
    ports:
      - 5000:3000
    command: "npm run dev"

volumes:
  db:
    driver: local