version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_EXPOSE_PORT}:5432"
    volumes:
      - db:/var/lib/postgresql/data/

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMIN_EXPOSE_PORT}:8080

  node:
    image: "node:18"
    user: "node"
    working_dir: /home/node/app
    environment:
      - TYPE_RUN_APP=${TYPE_RUN_APP}
    volumes:
      - ./:/home/node/app
    expose:
      - ${APP_EXPOSE_PORT}
    ports:
      - ${APP_EXPOSE_PORT}:3000
    command:
      - /bin/bash
      - -c
      - |
        if [[ $${TYPE_RUN_APP} == 'dev' ]]; then
          npm run dev
        else
          node ./.output/server/index.mjs
        fi

volumes:
  db:
    driver: local